language: node_js
node_js:
    - 6
    - "lts/*"
install:
  - npm install
  - npm install -g gulp
  - npm install -g gulp-cli
script:
  - npm test
  - gulp publish
cache:
  directories:
    - "node_modules"
branches:
  only:
  - master
  - develop
